Nazar/feature/validation_number_twillio
Simple2B/fish-market pull request #14
Opened 2022-12-06 08:31 UTC by Nazar-kob

Two new endpoints for phone number validation were created, the customer model was also updated, tests were added and the Twilio service was connected, but not completed yet

2022-12-06 09:07 UTC, Taraslysak approved these changes

2022-12-07 06:36 UTC, Taraslysak requested changes

2022-12-07 06:36 UTC, Taraslysak commented on backend/app/router/customer.py
> +        .filter(m.Customer.phone_number.in_([data.phone_number]))
Why ```in```, but not equals?

2022-12-07 06:36 UTC, Taraslysak commented on backend/app/router/customer.py
> +    "/valid",
I'd rather use ```validate```

2022-12-07 08:11 UTC, Nazar-kob commented on backend/app/router/customer.py
> +        .filter(m.Customer.phone_number.in_([data.phone_number]))
I'm thinking of the scenario that the number may be in two formats
I mean one - 380502221085
two - 0502221085

2022-12-07 08:11 UTC, Nazar-kob commented on backend/app/router/customer.py
> +    "/valid",
Thanks, I corrected

2022-12-07 10:10 UTC, kipod reviewed
Good job!!

2022-12-07 10:10 UTC, kipod commented on backend/app/model/utils.py
> +    return "".join([str(randint(0, 9)) for _ in range(6)])
here I suggest excluding value if it began from "0"

2022-12-07 10:10 UTC, kipod commented on backend/app/model/utils.py
> +    return "".join([str(randint(0, 9)) for _ in range(6)])
```python
def gen_confirm_code() -> str:
    value="0"
    while value[0] == "0":
        value = "".join([str(randint(0, 9)) for _ in range(6)])
    return value
```

2022-12-07 10:10 UTC, kipod commented on backend/app/router/customer.py
> +        .filter(m.Customer.phone_number.in_([data.phone_number]))
Agree with Taras ---> need compare full number value

2022-12-07 10:44 UTC, Nazar-kob commented on backend/app/config.py
> +    COUNTRY_CODE: str = "IL"
I got you

2022-12-07 10:57 UTC, Nazar-kob commented on backend/app/model/utils.py
> +    return "".join([str(randint(0, 9)) for _ in range(6)])
I agree with you

2022-12-07 11:12 UTC, merged