Nazar/feature/refacroting v1
Simple2B/fish-market pull request #32
Opened 2022-12-28 16:46 UTC by Nazar-kob

2022-12-29 13:52 UTC, Taraslysak requested changes

2022-12-29 13:52 UTC, Taraslysak commented on backend/app/router/order.py
> +    return s.OrdersOut(orders=db.query(m.Order).filter_by(business=business).all())
`return return s.OrdersOut(orders=business.orders.all())` ?

2022-12-29 13:52 UTC, Taraslysak commented on backend/app/router/phone_number.py
> +    )
Why cant we search for exact phone match here?

2022-12-29 13:52 UTC, Taraslysak commented on frontend/src/pages/Market/components/PersonalInfo/PersonalInfo.tsx
> +            },
No inline callbacks please

2022-12-29 17:02 UTC, Nazar-kob commented on backend/app/router/order.py
> +    return s.OrdersOut(orders=db.query(m.Order).filter_by(business=business).all())
Yes, the client's wish was to return all orders, even deleted ones

2022-12-29 17:04 UTC, Nazar-kob commented on backend/app/router/phone_number.py
> +    )
Sometimes the number can consist of 10 digits or 12 as you use here ilike

2022-12-29 17:09 UTC, Nazar-kob commented on frontend/src/pages/Market/components/PersonalInfo/PersonalInfo.tsx
> +            },
thanks done

2022-12-30 08:58 UTC, kipod approved these changes
10x

2022-12-30 08:58 UTC, merged